// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuditEntry struct {
	ID        string    `json:"id"`
	Timestamp time.Time `json:"timestamp"`
	Level     string    `json:"level"`
	Service   string    `json:"service"`
	Method    *string   `json:"method,omitempty"`
	Path      *string   `json:"path,omitempty"`
	Status    *int      `json:"status,omitempty"`
	Latency   *string   `json:"latency,omitempty"`
	Message   string    `json:"message"`
	SourceIP  *string   `json:"sourceIp,omitempty"`
	Tags      []string  `json:"tags,omitempty"`
}

type Connector struct {
	ID            string          `json:"id"`
	TenantID      string          `json:"tenantId"`
	Name          string          `json:"name"`
	ConnectorType ConnectorType   `json:"connectorType"`
	Status        ConnectorStatus `json:"status"`
	LastSyncAt    *time.Time      `json:"lastSyncAt,omitempty"`
	LastError     *string         `json:"lastError,omitempty"`
	CreatedAt     time.Time       `json:"createdAt"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

type ConnectorGroup struct {
	ExternalID  string  `json:"externalId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	GroupType   *string `json:"groupType,omitempty"`
}

type ConnectorHealth struct {
	ConnectorID    string `json:"connectorId"`
	ConnectorName  string `json:"connectorName"`
	Status         string `json:"status"`
	DeltaSupported bool   `json:"deltaSupported"`
	SupportsSchema bool   `json:"supportsSchema"`
}

type ConnectorUser struct {
	ExternalID  string  `json:"externalId"`
	Username    *string `json:"username,omitempty"`
	Email       *string `json:"email,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Department  *string `json:"department,omitempty"`
	Enabled     bool    `json:"enabled"`
}

type CreateConnectorInput struct {
	Name          string        `json:"name"`
	ConnectorType ConnectorType `json:"connectorType"`
	Config        any           `json:"config"`
}

type CreateIdentityInput struct {
	Type        IdentityType `json:"type"`
	Email       string       `json:"email"`
	DisplayName string       `json:"displayName"`
	Department  *string      `json:"department,omitempty"`
	EmployeeID  *string      `json:"employeeId,omitempty"`
	Source      *string      `json:"source,omitempty"`
	Attributes  any          `json:"attributes,omitempty"`
}

type HealthStatus struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type Identity struct {
	ID             string         `json:"id"`
	TenantID       string         `json:"tenantId"`
	Type           IdentityType   `json:"type"`
	Status         IdentityStatus `json:"status"`
	Email          string         `json:"email"`
	DisplayName    string         `json:"displayName"`
	Department     *string        `json:"department,omitempty"`
	EmployeeID     *string        `json:"employeeId,omitempty"`
	ManagerID      *string        `json:"managerId,omitempty"`
	Source         string         `json:"source"`
	RiskScore      float64        `json:"riskScore"`
	RiskFactors    []string       `json:"riskFactors"`
	AssuranceLevel string         `json:"assuranceLevel"`
	Attributes     any            `json:"attributes"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

type Mutation struct {
}

type NonHumanIdentity struct {
	ID          string         `json:"id"`
	TenantID    string         `json:"tenantId"`
	Name        string         `json:"name"`
	Type        IdentityType   `json:"type"`
	Status      IdentityStatus `json:"status"`
	AgentCardID *string        `json:"agentCardId,omitempty"`
	Protocols   []string       `json:"protocols"`
	OwnerID     *string        `json:"ownerId,omitempty"`
	TeamID      *string        `json:"teamId,omitempty"`
	IsGoverned  bool           `json:"isGoverned"`
	RiskScore   float64        `json:"riskScore"`
	ExpiresAt   *time.Time     `json:"expiresAt,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type Query struct {
}

type ReadinessChecks struct {
	Redis    string `json:"redis"`
	Postgres string `json:"postgres"`
	Neo4j    string `json:"neo4j"`
}

type ReadinessResult struct {
	Status string           `json:"status"`
	Checks *ReadinessChecks `json:"checks"`
}

type SyncConnectorInput struct {
	ConnectorID string `json:"connectorId"`
}

type UpdateIdentityInput struct {
	DisplayName *string         `json:"displayName,omitempty"`
	Department  *string         `json:"department,omitempty"`
	Email       *string         `json:"email,omitempty"`
	Status      *IdentityStatus `json:"status,omitempty"`
	Attributes  any             `json:"attributes,omitempty"`
}

type ConnectorStatus string

const (
	ConnectorStatusConnected          ConnectorStatus = "connected"
	ConnectorStatusDisconnected       ConnectorStatus = "disconnected"
	ConnectorStatusError              ConnectorStatus = "error"
	ConnectorStatusSyncing            ConnectorStatus = "syncing"
	ConnectorStatusFullSyncWithErrors ConnectorStatus = "full_sync_with_errors"
)

var AllConnectorStatus = []ConnectorStatus{
	ConnectorStatusConnected,
	ConnectorStatusDisconnected,
	ConnectorStatusError,
	ConnectorStatusSyncing,
	ConnectorStatusFullSyncWithErrors,
}

func (e ConnectorStatus) IsValid() bool {
	switch e {
	case ConnectorStatusConnected, ConnectorStatusDisconnected, ConnectorStatusError, ConnectorStatusSyncing, ConnectorStatusFullSyncWithErrors:
		return true
	}
	return false
}

func (e ConnectorStatus) String() string {
	return string(e)
}

func (e *ConnectorStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectorStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectorStatus", str)
	}
	return nil
}

func (e ConnectorStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ConnectorType string

const (
	ConnectorTypeEntraID         ConnectorType = "entra_id"
	ConnectorTypeLdap            ConnectorType = "ldap"
	ConnectorTypeActiveDirectory ConnectorType = "active_directory"
	ConnectorTypeScim            ConnectorType = "scim"
	ConnectorTypeOkta            ConnectorType = "okta"
	ConnectorTypeAWSIam          ConnectorType = "aws_iam"
	ConnectorTypeGCPIam          ConnectorType = "gcp_iam"
	ConnectorTypeGeneric         ConnectorType = "generic"
)

var AllConnectorType = []ConnectorType{
	ConnectorTypeEntraID,
	ConnectorTypeLdap,
	ConnectorTypeActiveDirectory,
	ConnectorTypeScim,
	ConnectorTypeOkta,
	ConnectorTypeAWSIam,
	ConnectorTypeGCPIam,
	ConnectorTypeGeneric,
}

func (e ConnectorType) IsValid() bool {
	switch e {
	case ConnectorTypeEntraID, ConnectorTypeLdap, ConnectorTypeActiveDirectory, ConnectorTypeScim, ConnectorTypeOkta, ConnectorTypeAWSIam, ConnectorTypeGCPIam, ConnectorTypeGeneric:
		return true
	}
	return false
}

func (e ConnectorType) String() string {
	return string(e)
}

func (e *ConnectorType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectorType", str)
	}
	return nil
}

func (e ConnectorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type IdentityStatus string

const (
	IdentityStatusActive        IdentityStatus = "ACTIVE"
	IdentityStatusInactive      IdentityStatus = "INACTIVE"
	IdentityStatusSuspended     IdentityStatus = "SUSPENDED"
	IdentityStatusTerminated    IdentityStatus = "TERMINATED"
	IdentityStatusRevoked       IdentityStatus = "REVOKED"
	IdentityStatusPendingReview IdentityStatus = "PENDING_REVIEW"
)

var AllIdentityStatus = []IdentityStatus{
	IdentityStatusActive,
	IdentityStatusInactive,
	IdentityStatusSuspended,
	IdentityStatusTerminated,
	IdentityStatusRevoked,
	IdentityStatusPendingReview,
}

func (e IdentityStatus) IsValid() bool {
	switch e {
	case IdentityStatusActive, IdentityStatusInactive, IdentityStatusSuspended, IdentityStatusTerminated, IdentityStatusRevoked, IdentityStatusPendingReview:
		return true
	}
	return false
}

func (e IdentityStatus) String() string {
	return string(e)
}

func (e *IdentityStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IdentityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IdentityStatus", str)
	}
	return nil
}

func (e IdentityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type IdentityType string

const (
	IdentityTypeHuman          IdentityType = "HUMAN"
	IdentityTypeServiceAccount IdentityType = "SERVICE_ACCOUNT"
	IdentityTypeAiAgent        IdentityType = "AI_AGENT"
	IdentityTypeRobot          IdentityType = "ROBOT"
	IdentityTypeIotDevice      IdentityType = "IOT_DEVICE"
	IdentityTypeRpaBot         IdentityType = "RPA_BOT"
	IdentityTypeAPIKey         IdentityType = "API_KEY"
)

var AllIdentityType = []IdentityType{
	IdentityTypeHuman,
	IdentityTypeServiceAccount,
	IdentityTypeAiAgent,
	IdentityTypeRobot,
	IdentityTypeIotDevice,
	IdentityTypeRpaBot,
	IdentityTypeAPIKey,
}

func (e IdentityType) IsValid() bool {
	switch e {
	case IdentityTypeHuman, IdentityTypeServiceAccount, IdentityTypeAiAgent, IdentityTypeRobot, IdentityTypeIotDevice, IdentityTypeRpaBot, IdentityTypeAPIKey:
		return true
	}
	return false
}

func (e IdentityType) String() string {
	return string(e)
}

func (e *IdentityType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IdentityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IdentityType", str)
	}
	return nil
}

func (e IdentityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
